import streamlit as st
import requests
from PIL import Image
import io
import pathlib
from fpdf import FPDF
import datetime


def load_css(file_path):
    with open(file_path, "r") as f:
        css = f.read()
    st.markdown(f"<style>{css}</style>", unsafe_allow_html=True)

# Load the CSS file
css_path = pathlib.Path("styles.css")  # Ensure this path is correct
load_css(css_path)


# Title of the app
st.markdown('<p class="title"> Brain Disorder Diagnosis AI</p>', unsafe_allow_html=True)

# Sidebar for Navigation
st.sidebar.markdown("<h2 class='header1'>Navigation</h2>", unsafe_allow_html=True)

app_mode = st.sidebar.selectbox("Choose the app mode", ["Diagnosis", "Chatbot"])
st.sidebar.markdown(
    '<h3 class="heading">📖 User Guide</h3>',
    unsafe_allow_html=True
)
st.sidebar.markdown(
    """
    <div class="custom-info">
        • <b>Diagnosis Mode</b>: Upload an MRI scan for analysis.<br><br>
        • <b>Chatbot Mode</b>: Ask AI questions about the diagnosis.<br><br>
        • <b>Results</b>: AI will show predictions with confidence scores.
    </div>
    """,
    unsafe_allow_html=True
)  

#  About AI Model
st.sidebar.markdown(
    '<h3 class="heading">🤖 About AI Model</h3>',
    unsafe_allow_html=True
)
st.sidebar.markdown('<p class="Ai"> Our AI uses deep learning to analyze MRI scans for brain disorders.</p>',unsafe_allow_html=True)

#  Contact & Support
st.sidebar.markdown(
    '<h3 class="heading">📞 Contact Us</h3>',
    unsafe_allow_html=True
)

st.sidebar.markdown(
    '<p class="email-text">✉️ Email: support@brainai.com</p>',   
    unsafe_allow_html=True
)
def generate_report(prediction, confidence):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", style='B', size=16)
    pdf.cell(200, 10, "Brain Disorder Diagnosis Report", ln=True, align='C')
    pdf.ln(10)

    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(10)

    pdf.cell(200, 10, f"Prediction: {prediction}", ln=True)
    pdf.cell(200, 10, f"Confidence Score: {confidence}%", ln=True)
    pdf.ln(10)
    
    pdf.set_font("Arial", style='B', size=12)
    pdf.cell(200, 10, "Analysis Summary:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, "The AI model has analyzed the uploaded MRI scan and detected patterns indicative of the disorder. The model's confidence score suggests the probability of the detected condition.")
    pdf.ln(10)

    # Recommendations
    pdf.set_font("Arial", style='B', size=12)
    pdf.cell(200, 10, "Recommendations:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, "- Consult a neurologist for further clinical evaluation.\n- Consider additional diagnostic tests such as PET scans.\n- Follow up regularly for further monitoring.")
    pdf.ln(10)

    # Disclaimer
    pdf.set_font("Arial", style='I', size=10)
    pdf.multi_cell(0, 10, "This report is AI-generated and should not be considered a definitive medical diagnosis. Please consult a healthcare professional for further guidance.")
    pdf.ln(10)

    # Footer
    pdf.set_font("Arial", style='B', size=12)
    pdf.cell(200, 10, "Generated by: Brain Disorder Diagnosis AI", ln=True, align='C')
    pdf.cell(200, 10, "Support Contact: support@brainai.com", ln=True, align='C')

    return pdf.output(dest='S').encode('latin1')


if app_mode == "Diagnosis":
    st.markdown('<h2 class="header">Upload MRI Scan for Analysis</h2>', unsafe_allow_html=True)

    uploaded_file = st.file_uploader("Upload an MRI scan (JPG, PNG, or DICOM)", type=["jpg", "png", "dcm"])
    
    if uploaded_file is not None:
        try:
           
            image = Image.open(uploaded_file)
            st.image(image, caption="Uploaded MRI Scan", use_container_width=True)
        except Exception as e:
            st.error("Error reading image. Make sure the file is a valid image format.")

        if st.button("Analyze MRI"):
            # Convert the file to bytes for the API
            file_bytes = uploaded_file.getvalue()
            files = {"file": file_bytes}
        try:
                response = requests.post("http://127.0.0.1:5000/analyze", files=files)
                data = response.json()
                st.success(f"Prediction: {data.get('result', 'N/A')}")
                st.info(f"Confidence Score: {data.get('confidence', 'N/A')}%")
                
                # Display Grad-CAM heatmap if provided by the backend
                if data.get("heatmap"):
                    # Assuming the backend returns an image URL or base64 string; here we expect a URL.
                    st.image(data["heatmap"], caption="Grad-CAM Heatmap", use_column_width=True)
                pdf_data = generate_report(prediction, confidence)
                st.markdown('<div class="report-container">', unsafe_allow_html=True)
                st.markdown('<h2 class="report-title">Diagnosis Report</h2>', unsafe_allow_html=True)

                st.markdown(f'<p class="report-text"><b>Prediction:</b> {prediction}</p>', unsafe_allow_html=True)
                st.markdown(f'<p class="report-text"><b>Confidence Score:</b> {confidence}%</p>', unsafe_allow_html=True)

                st.markdown('<div class="download-button-container">', unsafe_allow_html=True)
                st.download_button(
                label=" Download Report as PDF",
                data=pdf_data,
                file_name="diagnosis_report.pdf",
                mime="application/pdf"
                )
                st.markdown('</div>', unsafe_allow_html=True)
                st.markdown('</div>', unsafe_allow_html=True)
 
        except Exception as e:
                st.error(f"Error contacting the AI model: {e}")


if app_mode == "Chatbot":
    
    st.markdown('<h2 class="header">AI Chatbot for Diagnosis Explanation</h2>', unsafe_allow_html=True)

    st.markdown('<p style="font-size:20px; color:black;">Ask any question regarding the AI diagnosis, such as:</p>', unsafe_allow_html=True)

    st.write("- Why was this scan classified as Alzheimer’s-positive?")
    st.write("- What features did the model consider important?")
    
    user_question = st.text_input("Enter your question here:")
    
    if st.button("Send"):
        if user_question:
            try:
                # Create a payload with the user's question
                payload = {"question": user_question}
                response = requests.post("http://127.0.0.1:5000/chat", json=payload)
                data = response.json()
                st.write("**AI Explanation:**")
                st.write(data.get("answer", "No answer provided."))
            except Exception as e:
                st.error(f"⚠ Chatbot Error: {e}")
        else:
            st.warning("⚠ Please type a question first before sending.")

  


